// mission.sqm - 17:06:45 09/06/15, generated in 0.10 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

version = 12;

class Mission {
	addOns[] = {"bornholm", "bornholmlayers", "bornholmobjects", "A3_Soft_F_Car", "A3_Soft_F_Quadbike", "a3_soft_f_beta_quadbike", "A3_Boat_F_Civilian_Boat", "A3_Boat_F_Boat_Transport_01", "A3_Air_F_Heli_Light_01", "A3_Air_F_Heli_Heli_Transport_04", "A3_Air_F_Heli_Heli_Transport_03", "a3_characters_f_gamma", "A3_Characters_F_OPFOR", "A3_Characters_F_INDEP", "A3_Characters_F_Civil", "A3_epoch_config", "a3_characters_f", "A3_Data_F_Curator_Virtual"};
	addOnsAuto[] = {"a3_epoch_config", "bornholm"};
	randomSeed = 43857643;
	
	class Intel {
		briefingName = "Epoch Mod Bornholm";
		resistanceWest = 0;
		timeOfChanges = 28800;
		startWeather = 0;
		startWind = 0;
		forecastWeather = 0;
		forecastWind = 0;
		forecastWaves = 0;
		wavesForced = 1;
		windForced = 1;
		year = 2035;
		month = 6;
		day = 24;
		hour = 12;
		minute = 55;
		startFogDecay = 0.013;
		forecastFogDecay = 0.013;
	};
	
	class Groups {
		items = 100;
		
		class Item0 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13810.1, 81.9685, 6874.29};
					azimut = 136.241;
					special = NONE;
					id = 0;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item1 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13809.4, 80.81.9685, 6878.28};
					azimut = 130.016;
					special = NONE;
					id = 1;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item2 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13813.5, 81.9685, 6876.65};
					azimut = 130.016;
					special = NONE;
					id = 2;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item3 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13816.3, 81.9685, 6882.15};
					azimut = 130.016;
					special = NONE;
					id = 3;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item4 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13808.9, 81.9685, 6878.98};
					azimut = 130.016;
					special = NONE;
					id = 4;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item5 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13808, 81.9685, 6879.56};
					azimut = 130.016;
					special = NONE;
					id = 5;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item6 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13813.2, 81.9685, 6882.15};
					azimut = 130.016;
					special = NONE;
					id = 6;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item7 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13815.4, 81.9685, 6880.38};
					azimut = 130.016;
					special = NONE;
					id = 7;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item8 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13813.6, 81.9685, 6880.91};
					azimut = 130.016;
					special = NONE;
					id = 8;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item9 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13816.9, 81.9685, 6881.43};
					azimut = 130.016;
					special = NONE;
					id = 9;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item10 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13808.2, 81.9685, 6875.39};
					azimut = 130.016;
					special = NONE;
					id = 10;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item11 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13809.3, 81.9685, 6874.92};
					azimut = 130.016;
					special = NONE;
					id = 11;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item12 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13809.9, 81.9685, 6879.17};
					azimut = 130.016;
					special = NONE;
					id = 12;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item13 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13809.9, 81.9685, 6876.73};
					azimut = 130.016;
					special = NONE;
					id = 13;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item14 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13810.5, 81.9685, 6878.57};
					azimut = 130.016;
					special = NONE;
					id = 14;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item15 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13814.8, 81.9685, 6874.56};
					azimut = 130.016;
					special = NONE;
					id = 15;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item16 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13812, 81.9685, 6873.31};
					azimut = 130.016;
					special = NONE;
					id = 16;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item17 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13815.7, 81.9685, 6873.92};
					azimut = 130.016;
					special = NONE;
					id = 17;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item18 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13812.1, 81.9685, 6881.91};
					azimut = 130.016;
					special = NONE;
					id = 18;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item19 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13814.3, 81.9685, 6882.45};
					azimut = 130.016;
					special = NONE;
					id = 19;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item20 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13811.9, 81.9685, 6878.83};
					azimut = 136.241;
					special = NONE;
					id = 20;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item21 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13811.8, 81.9685, 6875.36};
					azimut = 130.016;
					special = NONE;
					id = 21;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item22 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13812.7, 81.9685, 6875.7};
					azimut = 130.016;
					special = NONE;
					id = 22;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item23 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13813.9, 81.9685, 6881.61};
					azimut = 130.016;
					special = NONE;
					id = 23;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item24 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13811.3, 81.9685, 6874.51};
					azimut = 130.016;
					special = NONE;
					id = 24;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item25 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13812.8, 81.9685, 6881.34};
					azimut = 130.016;
					special = NONE;
					id = 25;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item26 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13815.5, 81.9685, 6882.67};
					azimut = 130.016;
					special = NONE;
					id = 26;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item27 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13816.5, 81.9685, 6880.58};
					azimut = 130.016;
					special = NONE;
					id = 27;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item28 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13811, 81.9685, 6879.32};
					azimut = 130.016;
					special = NONE;
					id = 28;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item29 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13811.1, 81.9685, 6873.66};
					azimut = 130.016;
					special = NONE;
					id = 29;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item30 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13815.3, 81.9685, 6876.22};
					azimut = 130.016;
					special = NONE;
					id = 30;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item31 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13816.9, 81.9685, 6877.38};
					azimut = 130.016;
					special = NONE;
					id = 31;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item32 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13811.2, 81.9685, 6877.03};
					azimut = 130.016;
					special = NONE;
					id = 32;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item33 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13810.4, 81.9685, 6875.15};
					azimut = 130.016;
					special = NONE;
					id = 33;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item34 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13808.7, 81.9685, 6876.36};
					azimut = 130.016;
					special = NONE;
					id = 34;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item35 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13813.3, 81.9685, 6879.89};
					azimut = 130.016;
					special = NONE;
					id = 35;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item36 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13809.9, 81.9685, 6881.54};
					azimut = 130.016;
					special = NONE;
					id = 36;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item37 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13807.8, 81.9685, 6878.76};
					azimut = 130.016;
					special = NONE;
					id = 37;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item38 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13817.2, 81.9685, 6875.92};
					azimut = 130.016;
					special = NONE;
					id = 38;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item39 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13814.4, 81.9685, 6880.18};
					azimut = 130.016;
					special = NONE;
					id = 39;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item40 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13814.5, 81.9685, 6876.92};
					azimut = 136.241;
					special = NONE;
					id = 40;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item41 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13808, 81.9685, 6874.47};
					azimut = 130.016;
					special = NONE;
					id = 41;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item42 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13810.9, 81.9685, 6876.16};
					azimut = 130.016;
					special = NONE;
					id = 42;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item43 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13806.8, 81.9685, 6879.34};
					azimut = 130.016;
					special = NONE;
					id = 43;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item44 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13812.2, 81.9685, 6879.75};
					azimut = 130.016;
					special = NONE;
					id = 44;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item45 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13807.4, 81.9685, 6880.18};
					azimut = 130.016;
					special = NONE;
					id = 45;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item46 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13809.1, 81.9685, 6879.92};
					azimut = 130.016;
					special = NONE;
					id = 46;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item47 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13815.1, 81.9685, 6881.87};
					azimut = 130.016;
					special = NONE;
					id = 47;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item48 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13811.4, 81.9685, 6880.28};
					azimut = 130.016;
					special = NONE;
					id = 48;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item49 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13813, 81.9685, 6879.16};
					azimut = 130.016;
					special = NONE;
					id = 49;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item50 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13807.3, 81.9685, 6877.94};
					azimut = 130.016;
					special = NONE;
					id = 50;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item51 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13812.5, 81.9685, 6877.34};
					azimut = 130.016;
					special = NONE;
					id = 51;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item52 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13809.5, 81.9685, 6880.79};
					azimut = 130.016;
					special = NONE;
					id = 52;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item53 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13813.6, 81.9685, 6874.34};
					azimut = 130.016;
					special = NONE;
					id = 53;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item54 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13810.9, 81.9685, 6881.72};
					azimut = 130.016;
					special = NONE;
					id = 54;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item55 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13814.1, 81.9685, 6879.31};
					azimut = 130.016;
					special = NONE;
					id = 55;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item56 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13815.8, 81.9685, 6881.16};
					azimut = 130.016;
					special = NONE;
					id = 56;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item57 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13808.3, 81.9685, 6878.04};
					azimut = 130.016;
					special = NONE;
					id = 57;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item58 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13806.6, 81.9685, 6880.83};
					azimut = 130.016;
					special = NONE;
					id = 58;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item59 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13811.8, 81.9685, 6881.21};
					azimut = 130.016;
					special = NONE;
					id = 59;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item60 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13814.2, 81.9685, 6875.77};
					azimut = 136.241;
					special = NONE;
					id = 60;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item61 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13813.6, 81.9685, 6877.62};
					azimut = 130.016;
					special = NONE;
					id = 61;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item62 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13812.1, 81.9685, 6876.52};
					azimut = 130.016;
					special = NONE;
					id = 62;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item63 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13816.4, 81.9685, 6879.8};
					azimut = 130.016;
					special = NONE;
					id = 63;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item64 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13809.5, 81.9685, 6875.89};
					azimut = 130.016;
					special = NONE;
					id = 64;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item65 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13808.3, 81.9685, 6880.47};
					azimut = 130.016;
					special = NONE;
					id = 65;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item66 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13814.7, 81.9685, 6881.12};
					azimut = 130.016;
					special = NONE;
					id = 66;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item67 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13807.7, 81.9685, 6881.07};
					azimut = 130.016;
					special = NONE;
					id = 67;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item68 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13812.4, 81.9685, 6880.61};
					azimut = 130.016;
					special = NONE;
					id = 68;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item69 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13815.3, 81.9685, 6879.64};
					azimut = 130.016;
					special = NONE;
					id = 69;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item70 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13809.1, 81.9685, 6877.36};
					azimut = 130.016;
					special = NONE;
					id = 70;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item71 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13817.2, 81.9685, 6878.36};
					azimut = 130.016;
					special = NONE;
					id = 71;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item72 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13810.6, 81.9685, 6880.93};
					azimut = 130.016;
					special = NONE;
					id = 72;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item73 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13816, 81.9685, 6875.57};
					azimut = 130.016;
					special = NONE;
					id = 73;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item74 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13810.2, 81.9685, 6880.09};
					azimut = 130.016;
					special = NONE;
					id = 74;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item75 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13814.8, 81.9685, 6877.88};
					azimut = 130.016;
					special = NONE;
					id = 75;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item76 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13808.8, 81.9685, 6881.28};
					azimut = 130.016;
					special = NONE;
					id = 76;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item77 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13814.4, 81.9685, 6873.74};
					azimut = 130.016;
					special = NONE;
					id = 77;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item78 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13816, 81.9685, 6878.05};
					azimut = 130.016;
					special = NONE;
					id = 78;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item79 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13807.9, 81.9685, 6877.11};
					azimut = 130.016;
					special = NONE;
					id = 79;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item80 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13810.3, 81.9685, 6877.72};
					azimut = 130.016;
					special = NONE;
					id = 80;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item81 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13812.8, 81.9685, 6878.26};
					azimut = 130.016;
					special = NONE;
					id = 81;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item82 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13813.9, 81.9685, 6878.51};
					azimut = 130.016;
					special = NONE;
					id = 82;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item83 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13807.5, 81.9685, 6876.21};
					azimut = 130.016;
					special = NONE;
					id = 83;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item84 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13811.5, 81.9685, 6877.94};
					azimut = 130.016;
					special = NONE;
					id = 84;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item85 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13817.3, 81.9685, 6879.08};
					azimut = 130.016;
					special = NONE;
					id = 85;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item86 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13815.1, 81.9685, 6878.66};
					azimut = 130.016;
					special = NONE;
					id = 86;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item87 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13812.3, 81.9685, 6874.06};
					azimut = 130.016;
					special = NONE;
					id = 87;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item88 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13816.4, 81.9685, 6876.51};
					azimut = 130.016;
					special = NONE;
					id = 88;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item89 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13816.2, 81.9685, 6878.91};
					azimut = 130.016;
					special = NONE;
					id = 89;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item90 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13810, 81.9685, 6873.52};
					azimut = 130.016;
					special = NONE;
					id = 90;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item91 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13813.2, 81.9685, 6873.54};
					azimut = 130.016;
					special = NONE;
					id = 91;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item92 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13815.9, 81.9685, 6874.72};
					azimut = 130.016;
					special = NONE;
					id = 92;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item93 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13809, 81.9685, 6873.91};
					azimut = 130.016;
					special = NONE;
					id = 93;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item94 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13817.6, 81.9685, 6876.68};
					azimut = 130.016;
					special = NONE;
					id = 94;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item95 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13813.9, 81.9685, 6875.07};
					azimut = 130.016;
					special = NONE;
					id = 95;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item96 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13815.7, 81.9685, 6877.3};
					azimut = 130.016;
					special = NONE;
					id = 96;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item97 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13815, 81.9685, 6875.27};
					azimut = 130.016;
					special = NONE;
					id = 97;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item98 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13812.7, 81.9685, 6874.73};
					azimut = 130.016;
					special = NONE;
					id = 98;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
		
		class Item99 {
			side = CIV;
			
			class Vehicles {
				items = 1;
				
				class Item0 {
					position[] = {13817.1, 81.9685, 6875.34};
					azimut = 130.016;
					special = NONE;
					id = 99;
					side = CIV;
					vehicle = "VirtualMan_EPOCH";
					player = "PLAY CDG";
					leader = 1;
					skill = 0.6;
				};
			};
		};
	};
	
	class Markers {
		items = 3;
		
		class Item0 {
			position[] = {10058.3, 117.542, 9015.85};
			name = "center";
			type = "Empty";
		};
		
		class Item1 {
			position[] = {13812.7, 80.8744, 6877.92};
			name = "respawn_east";
			type = "Empty";
		};
		
		class Item2 {
			position[] = {13812.7, 80.8769, 6877.97};
			name = "respawn_west";
			type = "Empty";
		};
	};
};

class Intro {
	addOns[] = {"bornholm"};
	addOnsAuto[] = {"bornholm"};
	randomSeed = 25982387;
	
	class Intel {
		timeOfChanges = 1800;
		startWeather = 0.3;
		startWind = 0.1;
		startWaves = 0.1;
		forecastWeather = 0.3;
		forecastWind = 0.1;
		forecastWaves = 0.1;
		forecastLightnings = 0.1;
		year = 2035;
		month = 6;
		day = 24;
		hour = 12;
		minute = 0;
		startFogDecay = 0.013;
		forecastFogDecay = 0.013;
	};
};

class OutroWin {
	addOns[] = {"bornholm"};
	addOnsAuto[] = {"bornholm"};
	randomSeed = 12635739;
	
	class Intel {
		timeOfChanges = 1800;
		startWeather = 0.3;
		startWind = 0.1;
		startWaves = 0.1;
		forecastWeather = 0.3;
		forecastWind = 0.1;
		forecastWaves = 0.1;
		forecastLightnings = 0.1;
		year = 2035;
		month = 6;
		day = 24;
		hour = 12;
		minute = 0;
		startFogDecay = 0.013;
		forecastFogDecay = 0.013;
	};
};

class OutroLoose {
	addOns[] = {"bornholm"};
	addOnsAuto[] = {"bornholm"};
	randomSeed = 37826347;
	
	class Intel {
		timeOfChanges = 1800;
		startWeather = 0.3;
		startWind = 0.1;
		startWaves = 0.1;
		forecastWeather = 0.3;
		forecastWind = 0.1;
		forecastWaves = 0.1;
		forecastLightnings = 0.1;
		year = 2035;
		month = 6;
		day = 24;
		hour = 12;
		minute = 0;
		startFogDecay = 0.013;
		forecastFogDecay = 0.013;
	};
};
