// config.bin - 13:57:44 08/21/15, generated in 0.00 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

class CfgPatches {
	class exile_server {
		requiredVersion = 0.1;
		requiredAddons[] = {"exile_client", "exile_server_config"};
		units[] = {};
		weapons[] = {};
		magazines[] = {};
		ammo[] = {};
	};
};

class CfgFunctions {
	class ExileServer {
		class Bootstrap {
			file = "exile_server\bootstrap";
			
			class preInit {
				preInit = 1;
			};
			
			class postInit {
				postInit = 1;
			};
		};
		
		class FiniteStateMachine {
			file = "exile_server\fsm";
			
			class main {
				ext = ".fsm";
			};
		};
	};
};
