// Generated by unRap v1.06 by Kegetys
class CfgPatches {
	class exile_server_config {
		requiredVersion = 0.1;
		requiredAddons[] = {};
		units[] = {};
		weapons[] = {};
		magazines[] = {};
		ammo[] = {};
	};
};
