// config.bin - 16:52:58 08/21/15, generated in 0.18 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Enabled, Automatic comments: Enabled

#include "CfgPatches.hpp"
#include "CfgBuildings.hpp"
#include "CfgLootTables.hpp"
#include "CfgSettings.hpp"
