if !((vehicle player) isEqualTo player) exitWith {};
if (!("ItemRadio" in (assigneditems player))) exitWith { ["ErrorTitleAndText", ["Quadbike Deploy", "You need to have a radio equipped to spawn a Quadbike."]] call ExileClient_gui_toaster_addTemplateToast;};
if (ExileClientPlayerIsInCombat) exitWith { ["ErrorTitleAndText", ["Quadbike Deploy", "You cannot deploy a quadbike in combat."]] call ExileClient_gui_toaster_addTemplateToast;};
(findDisplay 24015) closeDisplay 0;
_spawnPos = player modelToWorld [0,2,0];
_spawnDir = (getDir player) -90;
player unlinkItem "ItemRadio";
_veh = createVehicle["Exile_Bike_QuadBike_Black", _spawnPos , [] ,0 , "NONE"];
_veh setDir _spawnDir;
["SuccessTitleAndText", ["Quadbike Deployed. Radio removed."]] call ExileClient_gui_toaster_addTemplateToast;
_veh addEventHandler ["getin", "'down' cutText ['WARNING: Deployed Quadbikes do not save through restarts','PLAIN DOWN'];"];